### ISSUE TITLE
"TypeError: 'Rectangle' object does not support indexing"

### ISSUE THREAD

**Issue by thelazydogsback** [Bergvca/pyspark_dist_explore#2]
Hello...
I am able to use pyspark_dist_explore.**hist**() without any issues, but when I use pyspark_dist_explore.**distplot**() on the same dataframe, I get the following error:

```
databricks/python/lib/python3.5/site-packages/pyspark_dist_explore/pyspark_dist_explore.py in <listcomp>(.0)
     82     histogram.add_data(x)
     83     n, bins, patches = histogram.plot_hist(axis, normed=True, **kwargs)
---> 84     colors = [patch[0].get_facecolor() for patch in patches]
     85     histogram.plot_density(axis, color=colors)
     86     return n, bins, patches
```
**TypeError: 'Rectangle' object does not support indexing"**

Any ideas?
thanks

**Comment by Bergvca** [comment]
Hi @thelazydogsback  - I haven't used this library (or pyspark) to often lately, however it could be that something has changed in matplotlib. It would make sense for it to be 
``colors = [patch.get_facecolor() for patch in patches]``

What is your version of matplotlib?

**Comment by vadakattu** [comment]
I'm seeing this issue running v 2.0.2

**Comment by vadakattu** [comment]
Raised PR #3 which seems to have fixed the issue.

**Comment by Bergvca** [comment]
Hi @thelazydogsback, the issue should be fixed now in the latest version on the Master branch. I will update it on Pypi if there are no other issues.
